services:
  postgres:
    container_name: node-api
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
      - ./data/pg:/data/postgres